name: Update progress

on:
  push:
    branches:
      - main

jobs:
  update-progress:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, ':memo:')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set timezone
        run: |
          export TZ="Asia/Seoul"

      - name: Set Git bot
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Extract commit authors
        id: extract_authors
        run: |
          authors=$(git log --format='%aN' --grep=':memo:' --since="$(date +%Y-%m-01) 00:00:00" | sort -u | awk '{gsub(/ /, "-", $0); printf "%s ", $0}')
          echo "AUTHORS=$authors" > $GITHUB_OUTPUT

      - name: Update progress
        run: |
          echo "### $(date +%Y)년 $(date +%m)월 진행상황" > progress/$(date +%Y)-$(date +%m).md
          echo -n "| 날짜 |" >> progress/$(date +%Y)-$(date +%m).md
          for author in ${AUTHORS[@]}; do
            author=${author//-/ }
            echo -n " $author |" >> progress/$(date +%Y)-$(date +%m).md
          done
          echo "" >> progress/$(date +%Y)-$(date +%m).md

          echo -n "|:---:|" >> progress/$(date +%Y)-$(date +%m).md
          for author in ${AUTHORS[@]}; do
            author=${author//-/ }
            echo -n ":---:|" >> progress/$(date +%Y)-$(date +%m).md
          done
          echo "" >> progress/$(date +%Y)-$(date +%m).md

          last_day=$(date -d "$(date +%Y-%m-01) +1 month -1 day" +%d)

          for ((i=1; i<=$last_day; i++)); do
            echo -n "| $(date +%m)월 $i일 |" >> progress/$(date +%Y)-$(date +%m).md
            if [[ "$i" -le "10#$(date +%d)" ]]; then
              for author in ${AUTHORS[@]}; do
                author=${author//-/ }
                if git log --since "$(date -d "$(date +%Y-%m-$i) 00:00:00")" --until "$(date -d "$(date +%Y-%m-$i) 23:59:59")" --author="$author" | grep .; then
                  echo -n " ✅ |" >> progress/$(date +%Y)-$(date +%m).md
                else
                  echo -n " ❌ |" >> progress/$(date +%Y)-$(date +%m).md
                fi
              done
              echo "" >> progress/$(date +%Y)-$(date +%m).md
            else
              for author in ${AUTHORS[@]}; do
                author=${author//-/ }
                echo -n " |" >> progress/$(date +%Y)-$(date +%m).md
              done
              echo "" >> progress/$(date +%Y)-$(date +%m).md
            fi
          done

          cd progress
          git add $(date +%Y)-$(date +%m).md
          git commit -m ":robot: Update progress by $COMMITTER_NAME"
          git push

        env:
          COMMITTER_NAME: ${{ github.actor }}
          AUTHORS: ${{ steps.extract_authors.outputs.authors }}
